" Payball's VIM configuration
"""""""""""""""""""""""""""""

" Defaults (generated by VimConfig.com)
"""""""""""""""""""""""""""""""""""""""

set expandtab                  " Converts tabs to spaces 
set noswapfile                 " Disables swap files
set nobackup nowritebackup     " Disables backup files
set encoding=utf-8             " Read encoding
set fileencoding=utf-8         " Saving encoding
set termencoding=utf-8         " Terminal encoding
set number                     " Show line numbers
set linebreak                  " Break lines at word (requires Wrap lines)
set showbreak=+++              " Wrap-broken line prefix
set textwidth=100              " Line wrap (number of cols)
set showmatch                  " Highlight matching brace
set visualbell                 " Use visual bell (no beeping)
set hlsearch                   " Highlight all search results
set smartcase                  " Enable smart-case search
set ignorecase                 " Always case-insensitive
set incsearch                  " Searches for strings incrementally
set autoindent                 " Auto-indent new lines
set shiftwidth=4               " Number of auto-indent spaces
set smartindent                " Enable smart-indent
set smarttab                   " Enable smart-tabs
set softtabstop=4              " Number of spaces per Tab
set ruler                      " Show row and column ruler information
set undolevels=1000            " Number of undo levels
set backspace=indent,eol,start " Backspace behaviour
"set cursorline                 " Draws an horizontal line at cursor position

" Plugins 
"""""""""

" Vundle config
set nocompatible " be IMproved
filetype off     " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Vundle Plugins
Plugin 'kien/ctrlp.vim'
Plugin 'bling/vim-airline'
Bundle 'scrooloose/nerdtree'
Bundle 'altercation/vim-colors-solarized'
Bundle 'godlygeek/tabular'
Bundle 'nanotech/jellybeans.vim'
Bundle 'vim-scripts/matchit.zip'
Bundle 'Raimondi/delimitMate'

call vundle#end()            " required
filetype plugin indent on    " required

" NERDTree
nmap <C-n> :NERDTreeToggle<CR>
let NERDTreeHighlightCursorline=1
let NERDTreeIgnore = ['tmp', '.yardoc', 'pkg']

" VIM Airline
set t_Co=256
set laststatus=2
let g:airline_powerline_fonts=1
let g:airline#extensions#tabline#enabled=0

" Themes
""""""""

" Solarized config
syntax enable
set background=dark "dark|light
let g:solarized_termcolors=256 "256 | 16
"colorscheme solarized

" Mappings
""""""""""

" Open VIMRC with shortcut
nnoremap <leader>ev :vsplit $MYVIMRC<cr> 

" Switch between buffers
nnoremap <silent> <C-Left> :bp<CR>
nnoremap <silent> <C-Right> :bn<CR>

" Switch between splits
nmap <silent> <A-Up> :wincmd k<CR>
nmap <silent> <A-Down> :wincmd j<CR>
nmap <silent> <A-Left> :wincmd h<CR>
nmap <silent> <A-Right> :wincmd l<CR>

" Hide higlighted matches after search
:nnoremap <silent> <CR> :nohlsearch<CR><CR>
